const block = {
  id: 0,
  title: 'Title',
  description: '',
  shots: 12,
  ballistic: 4,
  hits: 0,
  toughness: 4,
  strength: 4,
  wounds: 0,
  armorPen: 0,
  armorSave: 4,
  invulnSave: 6,
  rollToWound: 0,
  damage: 0,
  hitPercentage: 1,
  fnpAmount: 6,
  fnpChance: 1 / 6,
  fnpDamage: 0,
  woundPercentage: 0.5,
  savePercentage: 0,
  feelNoPain: false,
  reRollOnesHits: false,
  reRollOnesDamage: false,
  cover: false,
  editTitle: false,
  damagePerShot: 1,
  totalDamage: 0,
};

export default block;
